//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIdea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Category
    {
        public int AuthorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int AC_ID { get; set; }
    
        public virtual Blog_Author Blog_Author { get; set; }
        public virtual Blog_Category Blog_Category { get; set; }
    }
}
