//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIdea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> Views { get; set; }
        public int CategoryID { get; set; }
        public string BlogDescription { get; set; }
        public string BlogPicture { get; set; }
        public System.DateTime BlogDate { get; set; }
        public string BlogTitle { get; set; }
    
        public virtual Blog_Author Blog_Author { get; set; }
        public virtual Blog_Category Blog_Category { get; set; }
    }
}
