//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIdea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog_Author()
        {
            this.Auth_Category = new HashSet<Auth_Category>();
            this.Blogs = new HashSet<Blog>();
        }
    
        public int Auth_ID { get; set; }
        public int Name_ID { get; set; }
        public string Auth_Email { get; set; }
        public string Auth_Description { get; set; }
        public int RoleID { get; set; }
        public bool TopBlogger { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth_Category> Auth_Category { get; set; }
        public virtual Auth_Credentials Auth_Credentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
