//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIdea
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCred
    {
        public int U_ID { get; set; }
        public int NameID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
    
        public virtual Auth_Credentials Auth_Credentials { get; set; }
        public virtual Role Role { get; set; }
    }
}
